# Generated by Django 6.0.3 on 2026-03-14 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_activitylog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customers.customer'),
        ),
    ]
